client/src/components/Cards/Card.stories.js, client/src/components/Cards/index.js, client/src/components/Cards/style.js, client/src/components/Icon/icons/Tick.js, client/src/components/Icon/index.js
#18 
=======
---
---
---
Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)
- Project runs
- Code is consistent with agreed …
=> Create interactive card

README.md, client/src/components/CallUsLink/style.js, client/src/components/Cards/index.js, client/src/components/Cards/style.js, client/src/components/Inputs/Checkbox/style.js, client/src/components/Inputs/Dropdown/index.js, client/src/components/Inputs/Dropdown/style.js, client/src/components/Layout/General/style.js, client/src/components/Typography/index.js, client/src/pages/Home/index.js, client/src/pages/Home/style.js, client/src/pages/Step/index.js, client/src/pages/Step/style.js
=======
---
---
---
Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)
- Project runs
- Code is consistent with agreed team …
=> 0 update readme

client/src/components/Layout/General/style.js, client/src/pages/Home/index.js
#40 
=======
---
---
---
Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist and process review, please refer to Process Guide (#8)
- Project runs
- Code is consistent with agreed …
=> 40 fix crashing on last step

.vscode/settings.json, client/src/App.js, client/src/components/Typography/index.js, client/src/constants/nav-routes.js, client/src/pages/Login/index.js, client/src/pages/Welcome/Welcome1.js, client/src/pages/Welcome/Welcome2.js, client/src/pages/Welcome/index.js, client/src/pages/index.js
#77
=======
---
Couldn't find the demo video link @thejoefriel 
---
---
- Project runs
- …
=> Create admin into pages

client/src/App.js, client/src/constants/translations/english/index.js, client/src/pages/EditDetails/index.js, client/src/pages/EditDetails/style.js, client/src/pages/index.js, client/src/validation/fields.js, client/src/validation/schemas/edit-details.js, client/src/validation/schemas/index.js, package-lock.json
Relates #85
I've worked on the UI for the edit details page
**Note**: I used the update organization API call which might not be the correct one but plugging this page with any other API call shouldn't be tricky
=> build: edit details page (FE)

client/src/App.js, client/src/components/Route/index.js, client/src/constants/nav-routes.js, client/src/constants/roles.js, client/src/pages/CreateOrganisationDetails/SecondStep.js, client/src/pages/CreateOrganisationDetails/index.js, client/src/pages/CreateUniqueLink/Success.js, client/src/pages/CreateUniqueLink/index.js, client/src/pages/EditDetails/index.js, client/src/pages/Login/index.js, client/src/pages/Signup/index.js, server/database/dummy-data/organisations.js, server/modules/landing-page/controllers/index.js, server/modules/media/controllers/get-signed-url.js, server/modules/media/controllers/index.js, server/modules/organisation/controllers/get-organisation.js, server/modules/organisation/controllers/index.js, server/modules/organisation/controllers/update-organisation.js, server/modules/organisation/model/find.js, server/modules/organisation/use-cases/get-organisation.js, server/modules/organisation/use-cases/update-organisation.js, server/modules/user/controllers/signup.js, server/services/files-storage/get-file-pre-signed-url.js
#124 #115 
=======
---
---
---
- Project runs
- Tests all …
=> 124 fix create unique link bug

client/src/api-calls/organisations.js, client/src/pages/CreateUniqueLink/index.js, client/src/pages/EditDetails/index.js, client/src/pages/StepForm/index.js, client/src/validation/fields.js, client/src/validation/schemas/edit-details.js, server/modules/organisation/controllers/get-organisation.js, server/modules/organisation/controllers/update-organisation.js, server/modules/organisation/model/find.js, server/modules/organisation/model/update.js, server/modules/organisation/use-cases/get-organisation.js, server/modules/organisation/use-cases/update-organisation.js, server/modules/user/model/update.js
#85 
=======
---
---
---
- Project runs
- …
=> connect front with back for edit page

client/src/App.js, client/src/api-calls/content-audi-logs.js, client/src/pages/Changes/index.js, client/src/pages/Changes/style.js, client/src/pages/index.js, server/modules/content-audit-log/controllers/get-audit-log.js, server/modules/content-audit-log/controllers/get-audit-logs.js, server/modules/content-audit-log/controllers/index.js, server/modules/content-audit-log/model/find.js, server/modules/content-audit-log/use-cases/get-audit-logs.js, server/modules/content-audit-log/use-cases/index.js, server/modules/landing-page/controllers/update-landing-page.js, server/modules/landing-page/model/update.js, server/modules/landing-page/use-cases/update-landing-page.js, server/modules/step/controllers/update-step.js, server/modules/step/model/update.js, server/modules/step/use-cases/update-step.js
#134 
=======
---
---
---
- Project runs …
=> 134 create changes page

client/src/App.js, client/src/components/Inputs/ImageUpload/style.js, client/src/pages/Customise/index.js, client/src/pages/Customise/style.js, client/src/pages/index.js, client/src/validation/fields.js, client/src/validation/schemas/customise.js, client/src/validation/schemas/index.js, server/modules/organisation/model/find.js
Relates #133 
Building the customisation page and linking it to the backend
=> build: customise page

client/src/App.js, client/src/components/Inputs/ImageUpload/style.js, client/src/pages/Customise/index.js, client/src/pages/Customise/style.js, client/src/pages/index.js, client/src/validation/fields.js, client/src/validation/schemas/customise.js, client/src/validation/schemas/index.js, server/modules/organisation/model/find.js
=======
---
---
---
- Project runs
- No …
=> Client/133 customise page (REVERTED)

package-lock.json, package.json, server/config/server.js, server/database/dummy-data-prod/index.js, server/database/dummy-data-prod/organisations.js, server/database/dummy-data-prod/prod-data.js, server/database/dummy-data-prod/users.js
fix production deployment errors
=======
---
---
---
- Project runs
- Naming of files is consistent with …
=> fix production data

server/api/middlewares/helmet.js
=======
---
---
---
- Project runs
- No …
=> disable csp

client/src/components/Inputs/ImageUpload/index.js, server/services/files-storage/config.js
+ allow png on AWS S3, so we need to add this when we create the production bucket
=======
---
---
---
- Project runs
- Code is consistent with …
=> allow uploading png logos

client/src/pages/Admin/Customise/index.js, client/src/pages/Admin/EditDetails/index.js, server/database/connect.js, server/database/dummy-data-prod/prod-data.js, server/helpers/create-org-slug.js
=======
---
---
---
- Project runs
- No …
=> fix contact links bug in frontend

server/database/connect.js, server/helpers/create-org-slug.js
bug #1
=======
---
---
---
- Project runs …
=> replace replaceAll with replace #1

client/src/validation/fields.js
#158 
=======
---
---
---
- Project runs …
=> fix link validation

client/src/pages/Admin/CreateOrganisationDetails/SecondStep.js, client/src/pages/Admin/Customise/index.js, client/src/pages/Admin/ManageSteps/index.js
Have commented out draggable and colour content until we get the entire functionality sorted 
=======
---
---
---
- Project runs
- Code is …
=> Disable bonus

client/src/components/Cards/Cards.stories.js, client/src/components/HelpButton/index.js, client/src/components/Navbar/style.js, client/src/components/OrganisationLogo/index.js, client/src/pages/Admin/CreateOrganisationDetails/SecondStep.js, client/src/pages/Admin/CreateOrganisationDetails/index.js, client/src/pages/Admin/Dashboard/index.js, client/src/pages/Admin/EditDetails/index.js, client/src/pages/Admin/Organisations/index.js, client/src/pages/Home/style.js, client/src/pages/Signup/index.js, client/src/pages/Step/index.js, client/src/theme/index.js, server/database/dummy-data-prod/steps-content.js, server/modules/user/model/find.js
Fixes #163 
=======
---
---
---
- Project runs
- Tests all …
=> Copy fixes

client/src/context/admin-org.js, client/src/pages/Admin/CreateOrganisationDetails/index.js, client/src/pages/Admin/EditDetails/index.js
#166 
=======
---
---
---
- Project runs …
=> get fresh data after editing org details

client/src/components/Icon/index.js, client/src/pages/Step/index.js, client/src/pages/Step/style.js
#168 
=======
---
---
---
- Project runs …
=> fix close link

.gitignore, client/src/constants/nav-routes.js, client/src/pages/Admin/CreateOrganisationDetails/index.js, client/src/pages/Admin/EditDetails/index.js, client/src/pages/Step/index.js, client/src/validation/schemas/create-organisation-details.js, client/src/validation/schemas/edit-details.js, server/database/dummy-data-prod/steps-content.js
#171 
=======
---
---
---
- Project runs …
=> 171 copy changes

client/src/components/Layout/Dashboard/index.js, client/src/components/Navbar/index.js, client/src/components/Navbar/style.js, client/src/pages/Admin/EditDetails/index.js, client/src/pages/Step/index.js
#174 #176
=======
---
---
---
- Project runs
- Tests all …
=> Fix #176 #174

client/src/pages/Admin/Welcome/Welcome1.js, client/src/pages/Admin/Welcome/Welcome2.js
Fixes #175 
=======
---
---
---
- Project runs
- Tests all …
=> fixes #175

client/src/api-calls/organisations.js, client/src/pages/Admin/EditDetails/index.js, server/modules/organisation/controllers/get-organisation.js, server/modules/organisation/model/find.js, server/modules/organisation/use-cases/get-organisation.js, server/modules/organisation/use-cases/update-organisation.js
https://sentry.io/share/issue/48c2521aa41d4ba1bb95896a4b478d90/
=======
---
---
---
- Project runs
- …
=> handle duplicate email on edit details page

client/src/index.js
#190 
I think 10% would be within the limit, it was previously 50% 
=======
---
---
---
- Project runs
- …
=> update transaction rate

server/services/mailing/templates/index.js
Just reset the SendGrid setup to the new account that was sent by @Maggie via email 
the issue only to keep the reference 
#82
=======
---
---
---
- Project runs
- …
=> re setup sendgrid, change reset password templateid

.gitignore, client/.gitignore
CoL original PR: https://github.com/yalla-coop/cost-of-living-support/pull/2
=======
---
---
---
- Project runs
- Code is consistent with agreed …
=> update git ignore

client/src/components/Button/style.js, client/src/components/Grid/style.js, client/src/pages/Admin/StepForm/index.js
Related PR: https://github.com/yalla-coop/cost-of-living-support/pull/115
Related Issue: https://github.com/yalla-coop/cost-of-living-support/issues/14
\+ fix #221 
=======
---
---
---
- Project runs
- The new work has been checked with Axe accessibility checker and …
=> 14 preview button

client/src/api-calls/organisations.js, client/src/components/Grid/style.js, client/src/constants/nav-routes.js, client/src/pages/Admin/ConfirmRejection/index.js, client/src/pages/Admin/ConfirmRejection/style.js, client/src/pages/Admin/Organisations/UserRow.js, client/src/pages/Admin/Organisations/index.js, client/src/pages/Admin/index.js, client/src/validation/schemas/index.js, client/src/validation/schemas/reject-organisation.js, server/constants/data-type.js, server/modules/organisation/controllers/update-organisation-status.js, server/modules/organisation/use-cases/update-organisation-status.js, server/package-lock.json, server/services/mailing/templates/index.js, server/services/mailing/templates/templates-constants.js
related issue : https://github.com/yalla-coop/cost-of-living-support/issues/25
related PR : https://github.com/yalla-coop/cost-of-living-support/pull/109
=======
---
---
---
- Project runs
- The new work has been checked with Axe accessibility checker and doesn't …
=> handle admin approve and reject org

client/src/App.js, client/src/components/Language/LanguageBar/index.js, client/src/components/Language/index.js, client/src/components/Layout/General/index.js, client/src/components/Layout/General/style.js, client/src/components/Modal/style.js, client/src/components/Typography/index.js, client/src/constants/nav-routes.js, client/src/context/accessibility.js, client/src/pages/Accessibility/OverlayColor.js, client/src/pages/Accessibility/index.js, client/src/pages/Accessibility/style.js, client/src/theme/accessability-style.js, client/src/theme/global-style.js, client/src/theme/index.js
related PR : https://github.com/yalla-coop/cost-of-living-support/pull/111
related issue : https://github.com/yalla-coop/cost-of-living-support/issues/51
=======
---
---
---
- Project runs
- The new work has been checked with Axe accessibility checker and doesn't …
=> create accessibility features

client/src/components/Grid/style.js, client/src/constants/nav-routes.js, client/src/pages/Admin/ConfirmDeletion/index.js, client/src/pages/Admin/ConfirmDeletion/style.js, client/src/pages/Admin/EditDetails/index.js, client/src/pages/Admin/index.js, server/constants/data-type.js, server/database/init/migrations.sql, server/database/init/types.sql, server/database/migrations/20221201042815-add-deleted-status-for-organisations.js, server/database/migrations/sqls/20221201042815-add-deleted-status-for-organisations-down.sql, server/database/migrations/sqls/20221201042815-add-deleted-status-for-organisations-up.sql, server/database/models/organisations/schema.sql, server/modules/organisation/model/update.js, server/modules/organisation/use-cases/delete-organisation.js, server/modules/organisation/use-cases/index.js, server/modules/user/controllers/delete-user.js, server/modules/user/controllers/index.js, server/modules/user/use-cases/delete-user.js
related PR : https://github.com/yalla-coop/cost-of-living-support/pull/106/
related issue : https://github.com/yalla-coop/cost-of-living-support/issues/37
=======
---
---
---
- Project runs
- The new work has been checked with Axe accessibility checker and doesn't …
=> handle org delete account

server/modules/organisation/use-cases/update-organisation-status.js, server/modules/organisation/use-cases/update-organisation.js, server/modules/user/use-cases/reset-password-link.js, server/modules/user/use-cases/signup.js, server/services/mailing/templates/index.js, server/services/mailing/templates/templates-constants.js
Pr https://github.com/yalla-coop/cost-of-living-support/pull/120
=======
---
---
---
- Project runs
- …
=> Setup sendgrid templates

client/src/components/Inputs/Dropdown/index.js, client/src/pages/Accessibility/index.js
=> Add specific font style to dropdown

client/src/components/Language/LanguageBar/index.js, client/src/components/TextWithIcon/style.js
=> Fix for all routes

terraform/cloudformation-templates/s3_bucket.yml, terraform/production/locals.tf, terraform/production/providers.tf, terraform/production/terraform.tf, terraform/production/variables.tf, terraform/staging/locals.tf, terraform/staging/providers.tf, terraform/staging/terraform.tf, terraform/staging/variables.tf
=======
---
---
---
- Project runs
- No …
=> Added Terraform for S3 buckets

package.json
=======
---
---
---
- Project runs
- No …
=> Added cross-env to root package.json for Heroku build

client/src/components/Language/LanguageBar/index.js
=> Remove isText to fix accessibility link 

client/src/components/Language/LanguageBar/index.js
=======
---
---
---
- Project runs
- No …
=> Accessibility link

server/src/database/build-tables.js, server/src/database/init/migrations.sql, server/src/database/migrations/20221214173721-convert-json-to-jsonb.js, server/src/database/migrations/sqls/20221214173721-convert-json-to-jsonb-down.sql, server/src/database/migrations/sqls/20221214173721-convert-json-to-jsonb-up.sql
- migrate old json columns to jsonb
- fix "missing steps table" error
=======
---
---
---
- Project runs …
=> add migration files to convert to jsonb and fix build script

terraform/cloudformation-templates/s3_bucket.yml
Added translate permissions to AWS users
=> Added permissions for AWS user to use translate

client/src/components/Inputs/Dropdown/index.js, client/src/pages/Accessibility/index.js, client/src/pages/Accessibility/style.js
closes https://github.com/yalla-coop/cost-of-living-support/issues/208
=======
=> Fix font-family on Org dropdown

client/src/components/Layout/General/index.js
closes https://github.com/yalla-coop/cost-of-living-support/issues/206
=======
=> Remove footer message

client/src/App.js, client/src/hotJarConfig.js
closes https://github.com/yalla-coop/cost-of-living-support/issues/55
**Note:** Please see Hyde spreadsheet for HotJar login details or Bitwarden
=> Setup HotJar

client/src/constants/nav-routes.js
closes [#199](https://github.com/yalla-coop/cost-of-living-support/issues/199)
=======
=> Add t&c's and privacy policy

client/src/api-calls/landing-page.js, client/src/pages/Admin/Customise/index.js, client/src/pages/Admin/CustomiseResources/index.js, client/src/pages/Admin/EditLandingPage/index.js, client/src/pages/Admin/EditOrganisation/index.js, client/src/pages/Home/LandingContent.js, server/src/modules/landing-page/controllers/get-landing-page.js, server/src/modules/landing-page/use-cases/get-landing-page.js, server/src/modules/step/model/find.js, server/src/modules/step/use-cases/get-step.js
closes https://github.com/yalla-coop/cost-of-living-support/issues/212
closes https://github.com/yalla-coop/cost-of-living-support/issues/207
=======
---
---
---
- Project runs
- The new work has been checked with Axe accessibility checker and doesn't throw …
=> 212 207 fix forbidden and step bugs

client/src/components/HelpButton/index.js, client/src/pages/Admin/CustomiseResources/index.js
=> Fix duplicate contact details

client/src/constants/nav-routes.js, client/src/pages/Admin/Dashboard/index.js
=> Fix copy for UC admin page

client/src/components/Navbar/NavRoutes.js
=> Remove content review button

server/app.js, server/config/server.js
Note: Pushing this to prod will require to set a new env var:
HOST=HEROKU/HOST=AWS (either one depending on environment)
=======
---
---
---
- Project runs
- Linter …
=> fix CORS issue on Heroku / AWS

client/src/App.js
Issues this PR relates to 
closes https://github.com/yalla-coop/cost-of-living-support/issues/198
To test:
- Login to Cookiebot account (See Bitwarden)
- Use NGROK on your local dev enviroment
- Change the URL to your NGROK link
- Click save
- Visit NGROK link to test
- When done, revert back to original link
=======
=> Add Cookie banner

client/src/components/Cards/Tips/SingleTip.js, client/src/constants/common.js, client/src/pages/Accessibility/OverlayColor.js, server/src/database/dummy-data-prod/common.js, server/src/database/dummy-data-prod/steps-content.js, server/src/modules/landing-page/use-cases/get-landing-page.js, server/src/modules/translations/model/create.js, server/src/services/translation/translate-steps.js, server/src/services/translation/translation-api.js
- I have fixed all issues, but am not 100% I have fixed point 3:
It has been really inconsistent, sometimes it works great, other times it misses values resulting in empty spaces. I am not sure if it is to do with AWS or the recursive function found in `translation-api.js` or some other thing I don't know about.... if someone can test and let me know what they think it would be really appreciated! @RamyAlshurafa @dupreesi @remaininlight 
Note: run `npm run build:db` before testing
=> 201 - Fix various translation errors

server/src/database/migrations/sqls/20221123121141-add-org-status-up.sql, server/src/database/migrations/sqls/20221201042815-add-deleted-status-for-organisations-up.sql, server/src/database/migrations/sqls/20221214090033-add-languages-tables-down.sql, server/src/database/migrations/sqls/20221214090033-add-languages-tables-up.sql
I ran the migration files on the production DB and got a few errors 
=======
---
---
---
- Project runs …
=> fix migration files

server/src/api/middlewares/helmet.js
=======
---
---
---
- Project runs
- No …
=> update helmet to fix CORS

server/src/api/middlewares/helmet.js, server/src/database/build-tables.js, server/src/database/dummy-data-prod/landing-page-content-i18n.js, server/src/modules/landing-page/controllers/get-landing-page.js
=> Fix non-translated content after update

client/src/context/common.js, server/src/services/mailing/index.js, server/src/services/translation/translation-api.js
https://github.com/yalla-coop/cost-of-living-support/pull/233
=======
---
---
---
- Project runs
- …
=> fix Sentry errors

client/src/constants/nav-routes.js
> Issues this PR relates to https://github.com/yalla-coop/cost-of-living-support/issues/240
=> Update demo video link

client/src/constants/nav-routes.js, server/src/modules/organisation/use-cases/update-organisation-status.js
Closes https://github.com/yalla-coop/cost-of-living-support/issues/242
=======
---
---
---
- Project runs
- Code is consistent with agreed team …
=> fix organisation id update

client/src/components/Layout/SplitScreen/index.js, client/src/constants/nav-routes.js
=> Fix direction and scroll bar

client/src/context/public-org.js
=======
---
---
---
- Project runs
- No …
=> change default slug for hyde

server/src/constants/app-links.js
Fixes https://github.com/yalla-coop/cost-of-living-support/issues/256
but introduced here https://github.com/yalla-coop/universal-credit-support/pull/276
=======
---
---
---
- Project runs
- The new work has been checked with Axe accessibility checker and doesn't …
=> fix reset password bug
